web/routes/project.py
from datetime import date
from flask import Blueprint, render_template, request, g, redirect, url_for, session, send_file, flash
from sqlalchemy.exc import IntegrityError
from decorators import login_required, perm_to_view_required, perm_to_manage_required
from db import db, Project, ProjectMember, Requirement, RequirementTestCase, TestCase, Bug, BugTestCase
from utils import create_json, import_json
from forms import ProjectForm

bp = Blueprint('project', __name__, url_prefix='/project')

@bp.route('/')
@login_required
def index():
    projects = db.session.execute(db.select(Project).join(ProjectMember).filter(ProjectMember.user_id == g.user.id)).scalars().all()
    return render_template('project/index.html', projects=projects)

@bp.route('/select', methods=['GET', 'POST'])
@login_required
def select():
    if request.method == 'POST':
        session['project_id'] = request.form['project_id']
        return redirect(request.args.get('next') or url_for('project.index'))
    projects = db.session.execute(db.select(Project).join(ProjectMember).filter(ProjectMember.user_id == g.user.id)).scalars().all()
    return render_template('project/select.html', projects=projects)

@bp.route('/<int:project_id>')
@perm_to_view_required
def detail(project_id):
    project = db.get_or_404(Project, project_id)
    total_reqs = db.session.execute(db.select(db.func.count()).select_from(Requirement).filter_by(project_id=project.id)).scalar()
    total_tcs = db.session.execute(db.select(db.func.count()).select_from(TestCase).filter_by(project_id=project.id)).scalar()
    total_bugs = db.session.execute(db.select(db.func.count()).select_from(Bug).filter_by(project_id=project.id)).scalar()
    data = {
        "total_reqs": total_reqs,
        "total_tcs": total_tcs,
        "total_bugs": total_bugs
    }
    return render_template('project/detail.html', project=project, data=data)

@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = ProjectForm(request.form)
    if request.method == 'POST' and form.validate():
        try:
            project = Project(
                name=form.name.data,
                description=form.description.data,
                manager_id=g.user.id
            )
            db.session.add(project)
            db.session.flush()
            db.session.add(ProjectMember(project_id=project.id, user_id=g.user.id, role="manager"))
            db.session.commit()
            return redirect(url_for('project.detail', project_id=project.id))
        except IntegrityError:
            db.session.rollback()
            flash('Project with this name already exists.')
    return render_template('project/create.html', form=form)

@bp.route('/<int:project_id>/edit', methods=['GET', 'POST'])
@perm_to_manage_required
def edit(project_id):
    project = db.get_or_404(Project, project_id)
    form = ProjectForm(request.form, obj=project)
    if request.method == 'POST' and form.validate():
        try:
            project.name = form.name.data
            project.description = form.description.data
            db.session.commit()
            return redirect(url_for('project.detail', project_id=project_id))
        except IntegrityError:
            flash('Project with this name already exists.')
    return render_template('project/edit.html', form=form)

@bp.route('/<int:project_id>/delete', methods=['POST'])
@perm_to_manage_required
def delete(project_id):
    project = db.get_or_404(Project, project_id)
    db.session.delete(project)
    db.session.commit()
    return redirect(url_for('project.index'))

@bp.route('/<int:project_id>/export')
@perm_to_view_required
def export(project_id):
    project = db.get_or_404(Project, project_id)
    requirements = db.session.execute(db.select(Requirement).filter_by(project_id=project_id).order_by(Requirement.order.asc())).scalars().all()
    testcases = db.session.execute(db.select(TestCase).filter_by(project_id=project_id).order_by(TestCase.order.asc())).scalars().all()
    bugs = db.session.execute(db.select(Bug).filter_by(project_id=project_id).order_by(Bug.order.asc())).scalars().all()
    project_data = {
        'name': project.name,
        'description': project.description,
        'requirements': {
            req.code_with_prefix: {
                'title': req.title,
                'description': req.description,
                'type': req.type,
                'priority': req.priority
            } for req in requirements
        },
        'testcases': {
            tc.code_with_prefix: {
                'title': tc.title,
                'requirements': ', '.join(tc.requirements_codes),
                'preconditions': tc.preconditions,
                'steps': tc.steps,
                'expected_result': tc.expected_result
            } for tc in testcases
        },
        'bugs': {
            bug.code_with_prefix:{
                'title': bug.title,
                'description': bug.description,
                'testcases': ', '.join(bug.testcases_codes),
                'is_closed': bug.is_closed,
                'priority': bug.priority
            } for bug in bugs
        }
    }
    buffer = create_json(project_data)
    filename = f"{project.name.casefold()}_{date.today()}.json"
    return send_file(
        buffer,
        as_attachment=True,
        download_name=filename,
        mimetype='application/json'
    )

@bp.route('/import', methods=['GET', 'POST'])
@login_required
def import_project():
    if request.method == 'POST':
        file = request.files['file']
        if not file or not file.filename.endswith('.json'):
            flash('No file selected or incorrect file type.')
        else:
            data = import_json(file)
            try:
                project = Project(
                    name=data.get('name'),
                    description=data.get('description', ''),
                    manager_id=g.user.id
                )
                db.session.add(project)
                db.session.flush()
                project_member = ProjectMember(project_id=project.id, user_id=g.user.id, role="manager")
                db.session.add(project_member)
                reqs = {}
                order = 1
                for code, req_data in data.get('requirements', {}).items():
                    req = Requirement(
                        project_id=project.id,
                        title=req_data.get('title'),
                        description=req_data.get('description', ''),
                        type=req_data.get('type'),
                        priority=req_data.get('priority', 'high'),
                        order=order
                    )
                    db.session.add(req)
                    reqs[code] = req
                    order += 1
                db.session.flush()
                tcs = {}
                order = 1
                for code, tc_data in data.get('testcases', {}).items():
                    tc = TestCase(
                        project_id=project.id,
                        title=tc_data.get('title'),
                        preconditions=tc_data.get('preconditions'),
                        steps=tc_data.get('steps'),
                        expected_result=tc_data.get('expected_result'),
                        order=order
                    )
                    db.session.add(tc)
                    tcs[code] = tc
                    db.session.flush()
                    for req_code in tc_data.get('requirements', '').split(', '):
                        if req_code in reqs:
                            rtc = RequirementTestCase(
                                requirement_id=reqs[req_code].id,
                                test_case_id=tc.id
                            )
                            db.session.add(rtc)
                    order += 1
                order = 1
                for bug_data in data.get('bugs', {}).values():
                    bug = Bug(
                        project_id=project.id,
                        title=bug_data.get('title'),
                        description=bug_data.get('description'),
                        is_closed=bug_data.get('is_closed'),
                        priority=bug_data.get('priority'),
                        order=order
                    )
                    db.session.add(bug)
                    db.session.flush()
                    for tc_code in bug_data.get('testcases', '').split(', '):
                        if tc_code in tcs:
                            db.session.add(BugTestCase(bug_id=bug.id, test_case_id=tcs[tc_code].id))
                    order += 1
                db.session.commit()
                return redirect(url_for('project.detail', project_id=project.id))
            except IntegrityError:
                db.session.rollback()
                flash('Project with this name already exists.')
    return render_template('project/import.html')

@bp.before_app_request
def load_project():
    project_id = session.get('project_id')
    if project_id is None:
        g.project = None
    else:
        g.project = db.session.get(Project, project_id)

web/routes/testsuite.py
from flask import Blueprint, render_template, request, redirect, url_for, g
from decorators import perm_to_view_required, perm_to_edit_required
from db import db, TestSuite, TestCase, TestSuiteCase
from forms import TestSuiteForm

bp = Blueprint('testsuite', __name__, url_prefix='/testsuite')

@bp.route('/')
@perm_to_view_required
def index():
    testsuites = db.session.execute(db.select(TestSuite).filter_by(project_id=g.project.id).order_by(TestSuite.created_at.desc())).scalars().all()
    return render_template('testsuite/index.html', testsuites=testsuites)

@bp.route('/<int:testsuite_id>')
@perm_to_view_required
def detail(testsuite_id):
    testsuite = db.get_or_404(TestSuite, testsuite_id)
    tscs = db.session.execute(db.select(TestSuiteCase).filter_by(test_suite_id=testsuite_id).order_by(TestSuiteCase.order.asc())).scalars().all()
    return render_template('testsuite/detail.html', testsuite=testsuite, tscs=tscs)

@bp.route('/create', methods=['GET', 'POST'])
@perm_to_edit_required
def create():
    form = TestSuiteForm(request.form)
    if request.method == 'POST' and form.validate():
        testsuite = TestSuite(
            title=form.title.data,
            description=form.description.data,
            project_id=g.project.id
        )
        db.session.add(testsuite)
        db.session.flush()
        tcs_ids = request.form.getlist('testcases_ids')
        for idx, tc_id in enumerate(tcs_ids):
            db.session.add(TestSuiteCase(test_suite_id=testsuite.id, test_case_id=tc_id, order=idx + 1))
        db.session.commit()
        return redirect(url_for('testsuite.detail', testsuite_id=testsuite.id))
    testcases = db.session.execute(db.select(TestCase).filter_by(project_id=g.project.id).order_by(TestCase.order.asc())).scalars().all()
    return render_template('testsuite/create.html', form=form, testcases=testcases)

@bp.route('/<int:testsuite_id>/edit', methods=['GET', 'POST'])
@perm_to_edit_required
def edit(testsuite_id):
    testsuite = db.get_or_404(TestSuite, testsuite_id)
    form = TestSuiteForm(request.form, obj=testsuite)
    testcases = db.session.execute(db.select(TestCase).filter_by(project_id=g.project.id).order_by(TestCase.order.asc())).scalars().all()
    associated_ids = db.session.execute(db.select(TestSuiteCase.test_case_id).filter_by(test_suite_id=testsuite_id)).scalars().all()
    if request.method == 'POST' and form.validate():
        testsuite.title = form.title.data
        testsuite.description = form.description.data
        db.session.flush()
        tcs_ids = request.form.getlist('testcases_ids')
        last_order = db.session.execute(db.select(TestSuiteCase.order).filter_by(test_suite_id=testsuite_id).order_by(TestSuiteCase.order.desc()).limit(1)).scalars().first() or 0
        for tc in testcases:
            if str(tc.id) in tcs_ids and tc.id not in associated_ids:
                db.session.add(TestSuiteCase(test_suite_id=testsuite_id, test_case_id=tc.id, order=last_order + 1))
                last_order += 1
            elif str(tc.id) not in tcs_ids and tc.id in associated_ids:
                db.session.execute(db.delete(TestSuiteCase).where(TestSuiteCase.test_suite_id == testsuite_id, TestSuiteCase.test_case_id == tc.id))
        db.session.commit()
        return redirect(url_for('testsuite.detail', testsuite_id=testsuite.id))
    testcases = db.session.execute(db.select(TestCase).filter_by(project_id=g.project.id).order_by(TestCase.order.asc())).scalars().all()
    return render_template('testsuite/edit.html', form=form, testcases=testcases, associated_ids=associated_ids)

@bp.route('/<int:testsuite_id>/delete', methods=['POST'])
@perm_to_edit_required
def delete(testsuite_id):
    testsuite = db.get_or_404(TestSuite, testsuite_id)
    db.session.delete(testsuite)
    db.session.commit()
    return redirect(url_for('testsuite.index'))

@bp.route('/<int:testsuitecase_id1>/<int:testsuitecase_id2>/change_order', methods=['POST'])
@perm_to_edit_required
def change_order(testsuitecase_id1, testsuitecase_id2):
    tsc1 = db.get_or_404(TestSuiteCase, testsuitecase_id1)
    tsc2 = db.get_or_404(TestSuiteCase, testsuitecase_id2)
    tsc1.order, tsc2.order = tsc2.order, tsc1.order
    db.session.commit()
    return redirect(url_for('testsuite.detail', testsuite_id=tsc1.test_suite_id))

web/templates/testsuite/create.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<h2>Test Suite</h2>
<form method="post">
	<div class="mb-3">
		{{ render_field(form.title, class="form-control") }}
	</div>
	<div class="mb-3">
		{{ render_field(form.description, class="form-control") }}
	</div>
	<button type="submit" class="btn btn-primary">Create Test Suite</button>
	<a href="{{ url_for('testsuite.index') }}" class="btn btn-secondary">Back to List</a>
	{% if testcases %}
	<h2 class="mt-3">Associated Test Cases</h2>
	{% for tc in testcases %}
	<div class="form mb-3">
		<input type="checkbox" id="testcase_{{ tc.id }}" name="testcases_ids" value="{{ tc.id }}">
		<label for="testcase_{{ tc.id }}" class="form-label">{{ tc.code_with_prefix }} {{ tc.title }}</label>
	</div>
	{% endfor %}
	{% endif %}
</form>
{% endblock %}

web/templates/testsuite/detail.html
{% extends 'base.html' %}

{% block content %}
<h2>Test Suite</h2>

<p><strong>Name:</strong> {{ testsuite.title }}</p>
<p><strong>Description:</strong> {{ testsuite.description }}</p>
<p><strong>Total Test Cases:</strong> {{ tscs | length }}</p>
<p><strong>Created At:</strong> {{ testsuite.created_at | format_datetime }}</p>
<p><strong>Updated At:</strong> {{ testsuite.updated_at | format_datetime }}</p>

<form action="{{ url_for('testsuite.delete', testsuite_id=testsuite.id) }}" method="post" style="display:inline;" onsubmit="return confirm('Are you sure you want to delete this test suite?');">
	<a href="{{ url_for('testsuite.edit', testsuite_id=testsuite.id) }}" class="btn btn-secondary">Edit</a>
	<button type="submit" class="btn btn-danger">Delete</button>
	<a href="{{ url_for('testsuite.index') }}" class="btn btn-secondary">Back to List</a>
</form>

{% if tscs %}
<h3 class="mt-3">Associated Test Cases</h3>
<table class="table">
	<thead class="table-dark mt-3">
		<tr>
			<th>Order</th>
			<th>ID</th>
			<th>Title</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		{% for tsc in tscs %}
		<tr>
			<td>{{ loop.index }}</td>
			<td>{{ tsc.testcase_code }}</td>
			<td><a href="{{ url_for('testcase.detail', testcase_id=tsc.test_case_id) }}">{{ tsc.testcase_title }}</a></td>
			<td>
				{% if loop.index > 1 %}
				<form method="post" action="{{ url_for('testsuite.change_order', testsuitecase_id1=tsc.id, testsuitecase_id2=tscs[loop.index0 - 1].id) }}">
					<button type="submit" class="btn btn-sm btn-outline-primary">Move Up</button>
				</form>
				{% endif %}
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% else %}
<p>No associated test cases.</p>
{% endif %}
{% endblock %}

web/templates/testsuite/edit.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<h2>Test Suite Edit</h2>

<form method="post">
    <div class="mb-3">
        {{ render_field(form.title, class="form-control") }}
    </div>
    <div class="mbp-3">
        {{ render_field(form.description, class="form-control") }}
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    <a href="{{ url_for('testsuite.detail', testsuite_id=request.view_args['testsuite_id']) }}" class="btn btn-secondary">Cancel</a>
	{% if testcases %}
	<h2 class="mt-3">Associated Test Cases</h2>
	{% for tc in testcases %}
	<div class="form mb-3">
		<input type="checkbox" id="testcase_{{ tc.id }}" name="testcases_ids" value="{{ tc.id }}" {% if tc.id in associated_ids %}checked{% endif %}>
		<label for="testcase_{{ tc.id }}" class="form-label">{{ tc.code_with_prefix }} {{ tc.title }}</label>
	</div>
	{% endfor %}
	{% endif %}
</form>
{% endblock %}

web/templates/testsuite/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Test Suites</h2>

<div class="mb-3">
    <a href="{{ url_for('testsuite.create') }}" class="btn btn-primary">Create Test Suite</a>
    <a href="{{ url_for('project.select', next=url_for('testsuite.index')) }}" class="btn btn-secondary">Select Project</a>
</div>

<div class="list-group mb-3 mt-3">
    {% for testsuite in testsuites %}
    <a href="{{ url_for('testsuite.detail', testsuite_id=testsuite.id) }}" class="list-group-item list-group-item-action">{{ testsuite.title }}</a>
    {% else %}
    <p>No test suites available.</p>
    {% endfor %}
</div>
{% endblock %}