web/routes/bugtracking.py
from flask import Blueprint, render_template, request, redirect, url_for, g
from db import db, Bug, TestCase, BugTestCase
from decorators import perm_to_view_required, perm_to_edit_required
from forms import BugForm

bp = Blueprint('bugtracking', __name__, url_prefix='/bugtracking')

@bp.route('/')
@perm_to_view_required
def index():
    bugs = db.session.execute(db.select(Bug).filter_by(project_id=g.project.id).order_by(Bug.created_at.desc())).scalars().all()
    bugs.sort(key=lambda b: int(b.is_closed))
    total_open_bugs = sum(1 for bug in bugs if not bug.is_closed)
    high_open_bugs = sum(1 for bug in bugs if bug.priority == 'high')
    medium_open_bugs = sum(1 for bug in bugs if bug.priority == 'medium')
    low_open_bugs = total_open_bugs - high_open_bugs - medium_open_bugs
    data = {
        'open_bugs': total_open_bugs,
        'high_open_bugs': high_open_bugs,
        'medium_open_bugs': medium_open_bugs,
        'low_open_bugs': low_open_bugs
    }
    return render_template('bugtracking/index.html', bugs=bugs, data=data)

@bp.route('/create', methods=['GET', 'POST'])
@perm_to_edit_required
def create():
    form = BugForm(request.form)
    testcases = db.session.execute(db.select(TestCase).filter(TestCase.project_id == g.project.id)).scalars().all()
    if request.method == 'POST' and form.validate():
        bug = Bug(
            title=form.title.data,
            description=form.description.data,
            is_closed=form.is_closed.data,
            priority=form.priority.data,
            reported_by=g.user.id,
            project_id=g.project.id
        )
        bug.order = bug.last_order + 1
        db.session.add(bug)
        db.session.flush()
        tcs_ids = request.form.getlist('testcases_ids')
        for tc_id in tcs_ids:
            db.session.add(BugTestCase(bug_id=bug.id, test_case_id=tc_id))
        db.session.commit()
        return redirect(url_for('bugtracking.detail', bug_id=bug.id))
    return render_template('bugtracking/create.html', form=form, testcases=testcases)

@bp.route('/<int:bug_id>')
@perm_to_view_required
def detail(bug_id):
    bug = db.get_or_404(Bug, bug_id)
    testcases = db.session.execute(db.select(TestCase).join(BugTestCase).filter(BugTestCase.bug_id == bug_id)).scalars().all()
    return render_template('bugtracking/detail.html', bug=bug, testcases=testcases)

@bp.route('/<int:bug_id>/edit', methods=['GET', 'POST'])
@perm_to_edit_required
def edit(bug_id):
    bug = db.get_or_404(Bug, bug_id)
    form = BugForm(request.form, obj=bug)
    associated_ids = db.session.execute(db.select(BugTestCase.test_case_id).filter(BugTestCase.bug_id == bug_id)).scalars().all()
    testcases = db.session.execute(db.select(TestCase).filter(TestCase.project_id == g.project.id)).scalars().all()
    if request.method == 'POST' and form.validate():
        bug.title = form.title.data
        bug.description = form.description.data
        bug.is_closed = form.is_closed.data
        bug.priority = form.priority.data
        db.session.flush()
        tcs_ids = request.form.getlist('testcases_ids')
        for tc in testcases:
            if str(tc.id) in tcs_ids and tc.id not in associated_ids:
                db.session.add(BugTestCase(bug_id=bug.id, test_case_id=tc.id))
            elif str(tc.id) not in tcs_ids and tc.id in associated_ids:
                db.session.execute(db.delete(BugTestCase).filter_by(bug_id=bug.id, test_case_id=tc.id))
        db.session.commit()
        return redirect(url_for('bugtracking.detail', bug_id=bug.id))
    return render_template('bugtracking/edit.html', form=form, testcases=testcases, associated_ids=associated_ids)

@bp.route('/<int:bug_id>/update_status', methods=['POST'])
@perm_to_edit_required
def update_status(bug_id):
    bug = db.get_or_404(Bug, bug_id)
    bug.is_closed = not bug.is_closed
    db.session.commit()
    return redirect(url_for('bugtracking.index'))

@bp.route('/<int:bug_id>/delete', methods=['POST'])
@perm_to_edit_required
def delete(bug_id):
    bug = db.get_or_404(Bug, bug_id)
    db.session.delete(bug)
    db.session.commit()
    return redirect(url_for('bugtracking.index'))

web/routes/project.py
from datetime import date
from flask import Blueprint, render_template, request, g, redirect, url_for, session, send_file, flash
from sqlalchemy.exc import IntegrityError
from decorators import login_required, perm_to_view_required, perm_to_manage_required
from db import db, Project, ProjectMember, Requirement, RequirementTestCase, TestCase, Bug, BugTestCase
from utils import create_json, import_json
from forms import ProjectForm

bp = Blueprint('project', __name__, url_prefix='/project')

@bp.route('/')
@login_required
def index():
    projects = db.session.execute(db.select(Project).join(ProjectMember).filter(ProjectMember.user_id == g.user.id)).scalars().all()
    return render_template('project/index.html', projects=projects)

@bp.route('/select', methods=['GET', 'POST'])
@login_required
def select():
    if request.method == 'POST':
        session['project_id'] = request.form['project_id']
        return redirect(request.args.get('next') or url_for('project.index'))
    projects = db.session.execute(db.select(Project).join(ProjectMember).filter(ProjectMember.user_id == g.user.id)).scalars().all()
    return render_template('project/select.html', projects=projects)

@bp.route('/<int:project_id>')
@perm_to_view_required
def detail(project_id):
    project = db.get_or_404(Project, project_id)
    total_reqs = db.session.execute(db.select(db.func.count()).select_from(Requirement).filter_by(project_id=project.id)).scalar()
    total_tcs = db.session.execute(db.select(db.func.count()).select_from(TestCase).filter_by(project_id=project.id)).scalar()
    total_bugs = db.session.execute(db.select(db.func.count()).select_from(Bug).filter_by(project_id=project.id)).scalar()
    data = {
        "total_reqs": total_reqs,
        "total_tcs": total_tcs,
        "total_bugs": total_bugs
    }
    return render_template('project/detail.html', project=project, data=data)

@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = ProjectForm(request.form)
    if request.method == 'POST' and form.validate():
        try:
            project = Project(
                name=form.name.data,
                description=form.description.data,
                manager_id=g.user.id
            )
            db.session.add(project)
            db.session.flush()
            db.session.add(ProjectMember(project_id=project.id, user_id=g.user.id, role="manager"))
            db.session.commit()
            return redirect(url_for('project.detail', project_id=project.id))
        except IntegrityError:
            db.session.rollback()
            flash('Project with this name already exists.')
    return render_template('project/create.html', form=form)

@bp.route('/<int:project_id>/edit', methods=['GET', 'POST'])
@perm_to_manage_required
def edit(project_id):
    project = db.get_or_404(Project, project_id)
    form = ProjectForm(request.form, obj=project)
    if request.method == 'POST' and form.validate():
        try:
            project.name = form.name.data
            project.description = form.description.data
            db.session.commit()
            return redirect(url_for('project.detail', project_id=project_id))
        except IntegrityError:
            flash('Project with this name already exists.')
    return render_template('project/edit.html', form=form)

@bp.route('/<int:project_id>/delete', methods=['POST'])
@perm_to_manage_required
def delete(project_id):
    project = db.get_or_404(Project, project_id)
    db.session.delete(project)
    db.session.commit()
    return redirect(url_for('project.index'))

@bp.route('/<int:project_id>/export')
@perm_to_view_required
def export(project_id):
    project = db.get_or_404(Project, project_id)
    requirements = db.session.execute(db.select(Requirement).filter_by(project_id=project_id).order_by(Requirement.order.asc())).scalars().all()
    testcases = db.session.execute(db.select(TestCase).filter_by(project_id=project_id).order_by(TestCase.order.asc())).scalars().all()
    bugs = db.session.execute(db.select(Bug).filter_by(project_id=project_id).order_by(Bug.order.asc())).scalars().all()
    project_data = {
        'name': project.name,
        'description': project.description,
        'requirements': {
            req.code_with_prefix: {
                'title': req.title,
                'description': req.description,
                'type': req.type,
                'priority': req.priority
            } for req in requirements
        },
        'testcases': {
            tc.code_with_prefix: {
                'title': tc.title,
                'requirements': ', '.join(tc.requirements_codes),
                'preconditions': tc.preconditions,
                'steps': tc.steps,
                'expected_result': tc.expected_result
            } for tc in testcases
        },
        'bugs': {
            bug.code_with_prefix:{
                'title': bug.title,
                'description': bug.description,
                'testcases': ', '.join(bug.testcases_codes),
                'is_closed': bug.is_closed,
                'priority': bug.priority
            } for bug in bugs
        }
    }
    buffer = create_json(project_data)
    filename = f"{project.name.casefold()}_{date.today()}.json"
    return send_file(
        buffer,
        as_attachment=True,
        download_name=filename,
        mimetype='application/json'
    )

@bp.route('/import', methods=['GET', 'POST'])
@login_required
def import_project():
    if request.method == 'POST':
        file = request.files['file']
        if not file or not file.filename.endswith('.json'):
            flash('No file selected or incorrect file type.')
        else:
            data = import_json(file)
            try:
                project = Project(
                    name=data.get('name'),
                    description=data.get('description', ''),
                    manager_id=g.user.id
                )
                db.session.add(project)
                db.session.flush()
                project_member = ProjectMember(project_id=project.id, user_id=g.user.id, role="manager")
                db.session.add(project_member)
                reqs = {}
                order = 1
                for code, req_data in data.get('requirements', {}).items():
                    req = Requirement(
                        project_id=project.id,
                        title=req_data.get('title'),
                        description=req_data.get('description', ''),
                        type=req_data.get('type'),
                        priority=req_data.get('priority', 'high'),
                        order=order
                    )
                    db.session.add(req)
                    reqs[code] = req
                    order += 1
                db.session.flush()
                tcs = {}
                order = 1
                for code, tc_data in data.get('testcases', {}).items():
                    tc = TestCase(
                        project_id=project.id,
                        title=tc_data.get('title'),
                        preconditions=tc_data.get('preconditions'),
                        steps=tc_data.get('steps'),
                        expected_result=tc_data.get('expected_result'),
                        order=order
                    )
                    db.session.add(tc)
                    tcs[code] = tc
                    db.session.flush()
                    for req_code in tc_data.get('requirements', '').split(', '):
                        if req_code in reqs:
                            rtc = RequirementTestCase(
                                requirement_id=reqs[req_code].id,
                                test_case_id=tc.id
                            )
                            db.session.add(rtc)
                    order += 1
                order = 1
                for bug_data in data.get('bugs', {}).values():
                    bug = Bug(
                        project_id=project.id,
                        title=bug_data.get('title'),
                        description=bug_data.get('description'),
                        is_closed=bug_data.get('is_closed'),
                        priority=bug_data.get('priority'),
                        order=order
                    )
                    db.session.add(bug)
                    db.session.flush()
                    for tc_code in bug_data.get('testcases', '').split(', '):
                        if tc_code in tcs:
                            db.session.add(BugTestCase(bug_id=bug.id, test_case_id=tcs[tc_code].id))
                    order += 1
                db.session.commit()
                return redirect(url_for('project.detail', project_id=project.id))
            except IntegrityError:
                db.session.rollback()
                flash('Project with this name already exists.')
    return render_template('project/import.html')

@bp.before_app_request
def load_project():
    project_id = session.get('project_id')
    if project_id is None:
        g.project = None
    else:
        g.project = db.session.get(Project, project_id)

web/templates/bugtracking/create.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<h1>Bug Tracking</h1>
<form method="post">
	<div class="mb-3">
		{{ render_field(form.title, class="form-control") }}
	</div>
	<div class="mb-3">
		{{ render_field(form.description, class="form-control") }}
	</div>
	<div class="mb-3">
		{{ render_field(form.priority, class="form-select") }}
	</div>
	<div class="mb-3">
		{{ render_field(form.is_closed, class="form-select") }}
	</div>
	<button type="submit" class="btn btn-primary">Create Bug</button>
	<a href="{{ url_for('bugtracking.index') }}" class="btn btn-secondary">Back to List</a>
	{% if testcases %}
	<h2 class="mt-3">Associated Test Cases</h2>
	{% for tc in testcases %}
	<div class="form mb-3">
		<input type="checkbox" id="testcase_{{ tc.id }}" name="testcases_ids" value="{{ tc.id }}">
		<label for="testcase_{{ tc.id }}" class="form-label">{{ tc.code_with_prefix }} {{ tc.title }}</label>
	</div>
	{% endfor %}
	{% endif %}
</form>
{% endblock %}

web/templates/bugtracking/detail.html
{% extends 'base.html' %}

{% block content %}
<h2>Bug Tracking</h2>
<p><strong>ID:</strong> {{ bug.code_with_prefix }}</p>
<p><strong>Title:</strong> {{ bug.title }}</p>
<p><strong>Description:</strong> {{ bug.description }}</p>
<p><strong>Status:</strong> {{ bug.status }}</p>
<p><strong>Priority:</strong> {{ bug.priority | capitalize }}</p>
<p><strong>Reporter:</strong> {{ bug.reporter }}</p>
<p><strong>Created At:</strong> {{ bug.created_at | format_datetime }}</p>
<p><strong>Updated At:</strong> {{ bug.updated_at | format_datetime }}</p>
<form method="post" action="{{ url_for('bugtracking.delete', bug_id=bug.id) }}" style="display:inline;" onsubmit="return confirm('Are you sure you want to delete this bug?');">
    <a href="{{ url_for('bugtracking.edit', bug_id=bug.id) }}" class="btn btn-secondary">Edit</a>
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{{ url_for('bugtracking.index') }}" class="btn btn-secondary">Back to List</a>
</form>
{% if testcases %}
<h3 class="mt-3">Associated Test Cases</h3>
<div class="list-group">
{% for testcase in testcases %}
    <a href="{{ url_for('testcase.detail', testcase_id=testcase.id) }}" class="list-group-item list-group-item-action">{{ testcase.code_with_prefix }} - {{ testcase.title }}</a>
{% endfor %}
</div>
{% endif %}
{% endblock %}

web/templates/bugtracking/edit.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<h2>Bug Tracking</h2>
<form method="post">
	<div class="mb-3">
		{{ render_field(form.title, class="form-control") }}
	</div>
	<div class="mb-3">
		{{ render_field(form.description, class="form-control") }}
	</div>
	<div class="mb-3">
		{{ render_field(form.priority, class="form-select") }}
	</div>
	<div class="mb-3">
		{{ render_field(form.is_closed, class="form-select") }}
	</div>
	<button type="submit" class="btn btn-primary">Save</button>
	<a href="{{ url_for('bugtracking.detail', bug_id=request.view_args['bug_id']) }}" class="btn btn-secondary">Cancel</a>
	{% if testcases %}
	<h2 class="mt-3">Associated Test Cases</h2>
	{% for tc in testcases %}
	<div class="form mb-3">
		<input type="checkbox" id="testcase_{{ tc.id }}" name="testcases_ids" value="{{ tc.id }}" {% if tc.id in associated_ids %}checked{% endif %}>
		<label for="testcase_{{ tc.id }}" class="form-label">{{ tc.code_with_prefix }} {{ tc.title }}</label>
	</div>
	{% endfor %}
	{% endif %}
</form>
{% endblock %}

web/templates/bugtracking/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Bug Tracking</h2>
<p><strong>Total Bugs:</strong> {{ bugs | length }}</p>
<p><strong>Open Bugs:</strong> {{ data.open_bugs }}</p>
<p><strong>High Priority:</strong> {{ data.high_open_bugs }}</p>
<p><strong>Medium Priority:</strong> {{ data.medium_open_bugs }}</p>
<p><strong>Low Priority:</strong> {{ data.low_open_bugs }}</p>
<div class="mb-3">
	<a href="{{ url_for('bugtracking.create') }}" class="btn btn-primary">Report Bug</a>
	<a href="{{ url_for('project.select', next=url_for('bugtracking.index')) }}" class="btn btn-secondary">Select Project</a>
</div>
<table class="table mt-3">
	<thead class="table-dark mt-3">
		<tr>
			<th>ID</th>
			<th>Test Cases</th>
			<th>Title</th>
			<th>Status</th>
			<th>Priority</th>
			<th>Reporter</th>
			<th>Last Update</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		{% for bug in bugs %}
		<tr {% if bug.is_closed %}class="table-secondary"{% endif %}>
			<td>{{ bug.code_with_prefix }}</td>
			<td>{{ bug.testcases_codes | join(', ') }}</td>
			<td><a href="{{ url_for('bugtracking.detail', bug_id=bug.id) }}">{{ bug.title }}</a></td>
			<td>{{ bug.status }}</td>
			<td>{{ bug.priority | capitalize }}</td>
			<td>{{ bug.reporter }}</td>
			<td>{{ bug.updated_at | format_datetime }}</td>
			<td>
				<form action="{{ url_for('bugtracking.update_status', bug_id=bug.id) }}" method="post">
					<button type="submit" class="btn btn-secondary btn-sm">Update Status</button>
				</form>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}