web/routes/project.py
from datetime import date
from flask import Blueprint, render_template, request, g, redirect, url_for, session, send_file, flash
from sqlalchemy.exc import IntegrityError
from decorators import login_required, perm_to_view_required, perm_to_manage_required
from db import db, Project, ProjectMember, Requirement, RequirementTestCase, TestCase, Bug, BugTestCase
from utils import create_json, import_json
from forms import ProjectForm

bp = Blueprint('project', __name__, url_prefix='/project')

@bp.route('/')
@login_required
def index():
    projects = db.session.execute(db.select(Project).join(ProjectMember).filter(ProjectMember.user_id == g.user.id)).scalars().all()
    return render_template('project/index.html', projects=projects)

@bp.route('/select', methods=['GET', 'POST'])
@login_required
def select():
    if request.method == 'POST':
        session['project_id'] = request.form['project_id']
        return redirect(request.args.get('next') or url_for('project.index'))
    projects = db.session.execute(db.select(Project).join(ProjectMember).filter(ProjectMember.user_id == g.user.id)).scalars().all()
    return render_template('project/select.html', projects=projects)

@bp.route('/<int:project_id>')
@perm_to_view_required
def detail(project_id):
    project = db.get_or_404(Project, project_id)
    total_reqs = db.session.execute(db.select(db.func.count()).select_from(Requirement).filter_by(project_id=project.id)).scalar()
    total_tcs = db.session.execute(db.select(db.func.count()).select_from(TestCase).filter_by(project_id=project.id)).scalar()
    total_bugs = db.session.execute(db.select(db.func.count()).select_from(Bug).filter_by(project_id=project.id)).scalar()
    data = {
        "total_reqs": total_reqs,
        "total_tcs": total_tcs,
        "total_bugs": total_bugs
    }
    return render_template('project/detail.html', project=project, data=data)

@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = ProjectForm(request.form)
    if request.method == 'POST' and form.validate():
        try:
            project = Project(
                name=form.name.data,
                description=form.description.data,
                manager_id=g.user.id
            )
            db.session.add(project)
            db.session.flush()
            db.session.add(ProjectMember(project_id=project.id, user_id=g.user.id, role="manager"))
            db.session.commit()
            return redirect(url_for('project.detail', project_id=project.id))
        except IntegrityError:
            db.session.rollback()
            flash('Project with this name already exists.')
    return render_template('project/create.html', form=form)

@bp.route('/<int:project_id>/edit', methods=['GET', 'POST'])
@perm_to_manage_required
def edit(project_id):
    project = db.get_or_404(Project, project_id)
    form = ProjectForm(request.form, obj=project)
    if request.method == 'POST' and form.validate():
        try:
            project.name = form.name.data
            project.description = form.description.data
            db.session.commit()
            return redirect(url_for('project.detail', project_id=project_id))
        except IntegrityError:
            flash('Project with this name already exists.')
    return render_template('project/edit.html', form=form)

@bp.route('/<int:project_id>/delete', methods=['POST'])
@perm_to_manage_required
def delete(project_id):
    project = db.get_or_404(Project, project_id)
    db.session.delete(project)
    db.session.commit()
    return redirect(url_for('project.index'))

@bp.route('/<int:project_id>/export')
@perm_to_view_required
def export(project_id):
    project = db.get_or_404(Project, project_id)
    requirements = db.session.execute(db.select(Requirement).filter_by(project_id=project_id).order_by(Requirement.order.asc())).scalars().all()
    testcases = db.session.execute(db.select(TestCase).filter_by(project_id=project_id).order_by(TestCase.order.asc())).scalars().all()
    bugs = db.session.execute(db.select(Bug).filter_by(project_id=project_id).order_by(Bug.order.asc())).scalars().all()
    project_data = {
        'name': project.name,
        'description': project.description,
        'requirements': {
            req.code_with_prefix: {
                'title': req.title,
                'description': req.description,
                'type': req.type,
                'priority': req.priority
            } for req in requirements
        },
        'testcases': {
            tc.code_with_prefix: {
                'title': tc.title,
                'requirements': ', '.join(tc.requirements_codes),
                'preconditions': tc.preconditions,
                'steps': tc.steps,
                'expected_result': tc.expected_result
            } for tc in testcases
        },
        'bugs': {
            bug.code_with_prefix:{
                'title': bug.title,
                'description': bug.description,
                'testcases': ', '.join(bug.testcases_codes),
                'is_closed': bug.is_closed,
                'priority': bug.priority
            } for bug in bugs
        }
    }
    buffer = create_json(project_data)
    filename = f"{project.name.casefold()}_{date.today()}.json"
    return send_file(
        buffer,
        as_attachment=True,
        download_name=filename,
        mimetype='application/json'
    )

@bp.route('/import', methods=['GET', 'POST'])
@login_required
def import_project():
    if request.method == 'POST':
        file = request.files['file']
        if not file or not file.filename.endswith('.json'):
            flash('No file selected or incorrect file type.')
        else:
            data = import_json(file)
            try:
                project = Project(
                    name=data.get('name'),
                    description=data.get('description', ''),
                    manager_id=g.user.id
                )
                db.session.add(project)
                db.session.flush()
                project_member = ProjectMember(project_id=project.id, user_id=g.user.id, role="manager")
                db.session.add(project_member)
                reqs = {}
                order = 1
                for code, req_data in data.get('requirements', {}).items():
                    req = Requirement(
                        project_id=project.id,
                        title=req_data.get('title'),
                        description=req_data.get('description', ''),
                        type=req_data.get('type'),
                        priority=req_data.get('priority', 'high'),
                        order=order
                    )
                    db.session.add(req)
                    reqs[code] = req
                    order += 1
                db.session.flush()
                tcs = {}
                order = 1
                for code, tc_data in data.get('testcases', {}).items():
                    tc = TestCase(
                        project_id=project.id,
                        title=tc_data.get('title'),
                        preconditions=tc_data.get('preconditions'),
                        steps=tc_data.get('steps'),
                        expected_result=tc_data.get('expected_result'),
                        order=order
                    )
                    db.session.add(tc)
                    tcs[code] = tc
                    db.session.flush()
                    for req_code in tc_data.get('requirements', '').split(', '):
                        if req_code in reqs:
                            rtc = RequirementTestCase(
                                requirement_id=reqs[req_code].id,
                                test_case_id=tc.id
                            )
                            db.session.add(rtc)
                    order += 1
                order = 1
                for bug_data in data.get('bugs', {}).values():
                    bug = Bug(
                        project_id=project.id,
                        title=bug_data.get('title'),
                        description=bug_data.get('description'),
                        is_closed=bug_data.get('is_closed'),
                        priority=bug_data.get('priority'),
                        order=order
                    )
                    db.session.add(bug)
                    db.session.flush()
                    for tc_code in bug_data.get('testcases', '').split(', '):
                        if tc_code in tcs:
                            db.session.add(BugTestCase(bug_id=bug.id, test_case_id=tcs[tc_code].id))
                    order += 1
                db.session.commit()
                return redirect(url_for('project.detail', project_id=project.id))
            except IntegrityError:
                db.session.rollback()
                flash('Project with this name already exists.')
    return render_template('project/import.html')

@bp.before_app_request
def load_project():
    project_id = session.get('project_id')
    if project_id is None:
        g.project = None
    else:
        g.project = db.session.get(Project, project_id)

web/routes/testcase.py
from datetime import date
import re
from flask import Blueprint, render_template, request, redirect, url_for, g, Response
from decorators import perm_to_view_required, perm_to_edit_required
from utils import create_csv
from db import db, TestCase, Requirement, RequirementTestCase
from forms import TestCaseForm

def normalize_steps(steps):
    rows = re.sub(r'^\s*\d+[\.\-\)]?\s*', '', steps, flags=re.MULTILINE)
    rows = [row.strip() for row in rows.splitlines() if row.strip()]
    norm_steps = []
    for i, row in enumerate(rows, 1):
        row = re.sub(r'[\.\s,]+$', '', row).strip()
        if not re.search(r'[\.\?\!]$', row):
            row += '.'
        norm_steps.append(f"{i}. {row}")
    return "\n".join(norm_steps)

bp = Blueprint('testcase', __name__, url_prefix='/testcase')

@bp.route('/')
@perm_to_view_required
def index():
    testcases = db.session.execute(db.select(TestCase).filter_by(project_id=g.project.id).order_by(TestCase.order.asc())).scalars().all()
    return render_template('testcase/index.html', testcases=testcases)

@bp.route('/<int:testcase_id>')
@perm_to_view_required
def detail(testcase_id):
    testcase = db.get_or_404(TestCase, testcase_id)
    requirements = db.session.execute(db.select(Requirement).join(RequirementTestCase).filter(RequirementTestCase.test_case_id == testcase_id).order_by(Requirement.order.asc())).scalars().all()
    return render_template('testcase/detail.html', testcase=testcase, requirements=requirements)

@bp.route('/create', methods=['GET', 'POST'])
@perm_to_edit_required
def create():
    form = TestCaseForm(request.form)
    if request.method == 'POST' and form.validate():
        testcase = TestCase(
            title=form.title.data,
            preconditions=form.preconditions.data,
            steps=normalize_steps(form.steps.data),
            expected_result=form.expected_result.data,
            project_id=g.project.id
        )
        testcase.order = testcase.last_order + 1
        db.session.add(testcase)
        db.session.flush()
        reqs_ids = request.form.getlist('requirements_ids')
        for req_id in reqs_ids:
            db.session.add(RequirementTestCase(requirement_id=req_id, test_case_id=testcase.id))
        db.session.commit()
        return redirect(url_for('testcase.detail', testcase_id=testcase.id))
    tcs_data = db.session.execute(db.select(TestCase.title, TestCase.preconditions, TestCase.expected_result).filter_by(project_id=g.project.id)).all()
    suggestions = {
        'titles': {td[0] for td in tcs_data},
        'preconditions': {td[1] for td in tcs_data},
        'expected_results': {td[2] for td in tcs_data}
    }
    requirements = db.session.execute(db.select(Requirement).filter_by(project_id=g.project.id).order_by(Requirement.order.asc())).scalars().all()
    return render_template('testcase/create.html', form=form, requirements=requirements, suggestions=suggestions)

@bp.route('/<int:testcase_id>/edit', methods=['GET', 'POST'])
@perm_to_edit_required
def edit(testcase_id):
    testcase = db.get_or_404(TestCase, testcase_id)
    form = TestCaseForm(request.form, obj=testcase)
    requirements = db.session.execute(db.select(Requirement).filter_by(project_id=g.project.id).order_by(Requirement.order.asc())).scalars().all()
    associated_ids = db.session.execute(db.select(RequirementTestCase.requirement_id).filter_by(test_case_id=testcase_id)).scalars().all()
    if request.method == 'POST' and form.validate():
        testcase.title = form.title.data
        testcase.preconditions = form.preconditions.data
        testcase.steps = normalize_steps(form.steps.data)
        testcase.expected_result = form.expected_result.data
        db.session.flush()
        reqs_ids = request.form.getlist('requirements_ids')
        for req in requirements:
            if str(req.id) in reqs_ids and req.id not in associated_ids:
                db.session.add(RequirementTestCase(requirement_id=req.id, test_case_id=testcase.id))
            elif str(req.id) not in reqs_ids and req.id in associated_ids:
                db.session.execute(db.delete(RequirementTestCase).filter_by(requirement_id=req.id, test_case_id=testcase.id))
        db.session.commit()
        return redirect(url_for('testcase.detail', testcase_id=testcase.id))
    return render_template('testcase/edit.html', form=form, requirements=requirements, associated_ids=associated_ids)

@bp.route('/<int:testcase_id>/delete', methods=['POST'])
@perm_to_edit_required
def delete(testcase_id):
    testcase = db.get_or_404(TestCase, testcase_id)
    db.session.delete(testcase)
    db.session.flush()
    testcases = db.session.execute(db.select(TestCase).filter_by(project_id=g.project.id).order_by(TestCase.order.asc())).scalars().all()
    for index, tc in enumerate(testcases):
        tc.order = index + 1
    db.session.commit()
    return redirect(url_for('testcase.index'))

@bp.route('/reorder', methods=['GET'])
@perm_to_edit_required
def reorder():
    testcases = db.session.execute(db.select(TestCase).filter_by(project_id=g.project.id).order_by(TestCase.order.asc())).scalars().all()
    return render_template('testcase/reorder.html', testcases=testcases)

@bp.route('/<int:testcase_id1>/<int:testcase_id2>', methods=['POST'])
@perm_to_edit_required
def change_order(testcase_id1, testcase_id2):
    testcase1 = db.get_or_404(TestCase, testcase_id1)
    testcase2 = db.get_or_404(TestCase, testcase_id2)
    testcase1.order, testcase2.order = testcase2.order, testcase1.order
    db.session.commit()
    return redirect(url_for('testcase.reorder'))

@bp.route('/export', methods=['GET'])
@perm_to_view_required
def export():
    testcases = db.session.execute(db.select(TestCase).filter_by(project_id=g.project.id).order_by(TestCase.order.asc())).scalars().all()
    data = [("ID", "Title", "Requirements", "Preconditions", "Steps", "Expected Result")]
    for tc in testcases:
        data.append((tc.code_with_prefix, tc.title, ', '.join(tc.requirements_codes), tc.preconditions, tc.steps, tc.expected_result))
    csv_data = create_csv(data)
    filename = f"testcases_{g.project.name.casefold()}_{date.today()}.csv"
    response = Response(
        csv_data,
        mimetype='text/csv',
        headers={"Content-disposition": f"attachment; filename={filename}"}
    )
    return response

web/templates/testcase/create.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<h2>Test Case</h2>
<form method="post">
    <div class="mb-3">
        {{ render_field(form.title, class="form-control", list="title_suggestions", autocomplete="off", autofocus=True) }}
    </div>
    <div class="mb-3">
        {{ render_field(form.preconditions, class="form-control", list="precondition_suggestions", autocomplete="off") }}
    </div>
    <div class="mb-3">
        {{ render_field(form.steps, class="form-control") }}
    </div>
    <div class="mb-3">
        {{ render_field(form.expected_result, class="form-control", list="expected_result_suggestions", autocomplete="off") }}
    </div>
    <button type="submit" class="btn btn-primary">Create Test Case</button>
    <a href="{{ url_for('testcase.index') }}" class="btn btn-secondary">Back to List</a>
	{% if requirements %}
	<h2 class="mt-3">Associated Requirements</h2>
	{% for req in requirements %}
	<div class="form mb-3">
		<input type="checkbox" id="requirement_{{ req.id }}" name="requirements_ids" value="{{ req.id }}">
		<label for="requirement_{{ req.id }}" class="form-label">{{req.code_with_prefix}} {{ req.title }}</label>
	</div>
	{% endfor %}
	{% endif %}
</form>

<datalist id="title_suggestions">
    {% for title in suggestions.titles %}
    <option value="{{ title }}">
    {% endfor %}
</datalist>

<datalist id="precondition_suggestions">
    {% for precondition in suggestions.preconditions %}
    <option value="{{ precondition }}">
    {% endfor %}
</datalist>

<datalist id="expected_result_suggestions">
    {% for expected_result in suggestions.expected_results %}
    <option value="{{ expected_result }}">
    {% endfor %}
</datalist>
{% endblock %}

web/templates/testcase/detail.html
{% extends 'base.html' %}

{% block content %}
<h2>Test Case</h2>

<p><strong>ID:</strong> {{ testcase.code_with_prefix }}</p>
<p><strong>Title:</strong> {{ testcase.title }}</p>
<p><strong>Preconditions:</strong> {{ testcase.preconditions }}</p>
<p><strong>Steps:</strong> {{ testcase.steps | replace('\n','<br/>') | safe }}</p>
<p><strong>Expected Result:</strong> {{ testcase.expected_result }}</p>
<p><strong>Created At:</strong> {{ testcase.created_at | format_datetime }}</p>
<p><strong>Updated At:</strong> {{ testcase.updated_at | format_datetime }}</p>

<form action="{{ url_for('testcase.delete', testcase_id=testcase.id) }}" method="post" style="display:inline;" onsubmit="return confirm('Are you sure you want to delete this test case?');">
    <a href="{{ url_for('testcase.edit', testcase_id=testcase.id) }}" class="btn btn-secondary">Edit</a>
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{{ url_for('testcase.index') }}" class="btn btn-secondary">Back to List</a>
</form>

{% if requirements %}
<h3 class="mt-3">Associated Requirements</h3>

<div class="list-group">
{% for requirement in requirements %}
    <a href="{{ url_for('requirement.detail', requirement_id=requirement.id) }}" class="list-group-item list-group-item-action">{{ requirement.code_with_prefix }} - {{ requirement.title }}</a>
{% endfor %}
</div>
{% endif %}
{% endblock %}

web/templates/testcase/edit.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<h2>Test Case Edit</h2>
<form method="post">
    <div class="mb-3">
        {{ render_field(form.title, class="form-control") }}
    </div>
    <div class="mb-3">
        {{ render_field(form.preconditions, class="form-control") }}
    </div>
    <div class="mb-3">
        {{ render_field(form.steps, class="form-control") }}
    </div>
    <div class="mb-3">
        {{ render_field(form.expected_result, class="form-control") }}
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    <a href="{{ url_for('testcase.detail', testcase_id=request.view_args['testcase_id']) }}" class="btn btn-secondary">Cancel</a>
	{% if requirements %}
	<h2 class="mt-3">Associated Requirements</h2>
	{% for req in requirements %}
	<div class="form mb-3">
		<input type="checkbox" id="requirement_{{ req.id }}" name="requirements_ids" value="{{ req.id }}" {% if req.id in associated_ids %}checked{% endif %}>
		<label for="requirement_{{ req.id }}" class="form-label">{{req.code_with_prefix}} {{ req.title }}</label>
	</div>
	{% endfor %}
	{% endif %}
</form>
{% endblock %}

web/templates/testcase/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Test Cases</h2>

<div class="mb-3">
	<a href="{{ url_for('testcase.create') }}" class="btn btn-primary">Create Test Case</a>
	<a href="{{ url_for('project.select', next=url_for('testcase.index')) }}" class="btn btn-secondary">Select Project</a>
	<a href="{{ url_for('testcase.reorder') }}" class="btn btn-secondary">Reorder Test Cases</a>
	<a href="{{ url_for('testcase.export') }}" class="btn btn-info">Export CSV</a>
</div>

{% if testcases %}
<table class="table">
	<thead class="table-dark mt-3">
		<tr>
			<th>ID</th>
			<th>Requirements</th>
			<th>Title</th>
			<th>Preconditions</th>
			<th>Steps</th>
			<th>Expected Result</th>
			<th>Last Update</th>
		</tr>
	</thead>
	<tbody>
		{% for testcase in testcases %}
		<tr>
			<td>{{ testcase.code_with_prefix }}</td>
			<td>{{ testcase.requirements_codes | join(', ') }}</td>
			<td><a href="{{ url_for('testcase.detail', testcase_id=testcase.id) }}" class="text-primary">{{ testcase.title }}</a></td>
			<td>{{ testcase.preconditions }}</td>
			<td>{{ testcase.steps | replace('\n','<br/>') | safe  }}</td>
			<td>{{ testcase.expected_result }}</td>
			<td>{{ testcase.updated_at | format_datetime }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% else %}
<p>No test cases found.</p>
{% endif %}
{% endblock %}

web/templates/testcase/reorder.html
{% extends 'base.html' %}

{% block content %}
<h2>Reorder Test Cases</h2>

<div class="mb-3">
    <a href="{{ url_for('testcase.index') }}" class="btn btn-secondary">Back to List</a>
</div>

<table class="table mt-3">
    <thead class="table-dark table-striped table-bordered">
        <tr>
            <th>Order</th>
            <th>Requirements</th>
            <th>Title</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for testcase in testcases %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>{{ testcase.requirements_codes | join(', ') }}</td>
            <td>{{ testcase.title }}</td>
            <td>
                {% if loop.index > 1 %}
                <form method="post" action="{{ url_for('testcase.change_order', testcase_id1=testcase.id, testcase_id2=testcases[loop.index0 - 1].id) }}">
                    <button type="submit" class="btn btn-sm btn-outline-primary">Move Up</button>
                </form>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}